# tasks file for megacli
---
- name: install dependencies
  apt:
    name: "{{ megacli_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - megacli
    - megacli-dependencies

- name: create (upload) directory
  file:
    path: "{{ megacli_upload_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - megacli
    - megacli-download

- name: upload
  copy:
    src: "{{ megacli_upload_path.lstrip('/') }}/MegaCli.zip"
    dest: "{{ megacli_upload_path }}/MegaCli.zip"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - megacli
    - megacli-upload

- name: install
  unarchive:
    src: "{{ megacli_upload_path }}/MegaCli.zip"
    dest: "{{ megacli_install_path }}"
    creates: "{{ megacli_install_path }}/MegaCli64"
    copy: false
  tags:
    - configuration
    - megacli
    - megacli-install
