# tasks file for megacli
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: megacli_dependencies
  tags: [configuration, megacli, megacli-dependencies]

- name: create (upload) directory
  file:
    path: "{{ megacli_upload_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, megacli, megacli-download]

- name: upload
  copy:
    src: var/lib/ansible/megacli/uploads/MegaCli.zip 
    dest: "{{ megacli_upload_path }}/MegaCli.zip" 
    owner: root
    group: root
    mode: 0644
  tags: [configuration, megacli, megacli-upload]

- name: create (install) directory
  file:
    path: "{{ megacli_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, megacli, megacli-install]

- name: install
  unarchive:
    src: "{{ megacli_upload_path }}/MegaCli.zip"
    dest: "{{ megacli_install_path }}"
    creates: "{{ megacli_install_path }}/MegaCli64"
    copy: false
  tags: [configuration, megacli, megacli-install]
